FROM node:12-alpine as build

WORKDIR /usr/local/post-microservice

COPY dist/apps/service-post package.json .env ./

RUN npm install --production

FROM node:12-alpine

WORKDIR /usr/local/post-microservice

COPY --from=build /usr/local/post-microservice .

ENV NODE_ENV=production

CMD ["node", "main.js"]