services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: password
            PG_DATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - postgres
        restart: unless-stopped
    user-service:
        container_name: user-service
        image: postgres
        environment:
            POSTGRES_DB: user
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        volumes:
            - ./database/user-service:/data/postgres
        expose:
            - "5441"
        ports:
            - "5441:5432"
        networks:
            - postgres
        restart: always
    security-service:
        container_name: security-service
        image: postgres
        environment:
            POSTGRES_DB: security
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        volumes:
            - ./database/security-service:/data/postgres
        expose:
            - "5442"
        ports:
            - "5442:5432"
        networks:
            - postgres
        restart: always
    file-service:
        container_name: file-service
        image: postgres
        environment:
            POSTGRES_DB: file
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        volumes:
            - ./database/file-service:/data/postgres
        expose:
            - "5443"
        ports:
            - "5443:5432"
        networks:
            - postgres
        restart: always
    follower-service:
        container_name: follower-service
        image: postgres
        environment:
            POSTGRES_DB: user
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        volumes:
            - ./database/follower-service:/data/postgres
        expose:
            - "5444"
        ports:
            - "5444:5432"
        networks:
            - postgres
        restart: always
    eureka-server:
        build:
            context: ./eureka-server
            dockerfile: ./Dockerfile
        image: eureka-server
        container_name: eureka-server
        ports:
            - "8761:8761"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
#    api-gateway:
#        build: ./api-gateway
#        image: api-gateway
#        container_name: api-gateway
#        ports:
#            - "8765:8765"
#        expose:
#            - "8765"
#        environment:
#            - SPRING_PROFILES_ACTIVE=docker
#            - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
#        depends_on:
#            - eureka-server
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        restart: unless-stopped
        networks:
            - kafka-net
    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        restart: unless-stopped
        networks:
            - kafka-net

networks:
    postgres:
        driver: bridge
    kafka-net:
        driver: bridge

volumes:

    postgres:
    pgadmin: